set(SRC_FILES
    AppStart.cpp
    AppUpdate.cpp
    AppEnd.cpp
    BackgroundImage.cpp
    Button.cpp
    Phase/CatBase.cpp
    Phase/StageSelection.cpp
    UnitData.cpp
    DatabaseManager.cpp
    Phase.cpp
)

set(INCLUDE_FILES
    App.hpp
    BackgroundImage.hpp
    Button.hpp
    ImageScaling.hpp
    SystemInfo.hpp
    Phase/CatBase.hpp
    Phase/StageSelection.hpp
    UnitData.hpp
    nlohmann/json.hpp
    DatabaseManager.hpp
    IStateful.hpp
    Phase.hpp
)

set(TEST_FILES
)
