set(SRC_FILES
    AppStart.cpp
    AppUpdate.cpp
    AppEnd.cpp
    Component/BackgroundImage.cpp
    Component/Button.cpp
    Phase/CatBase.cpp
    Phase/StageSelection.cpp
    UnitData.cpp
    DatabaseManager.cpp
    Phase.cpp
    Phase/Upgrade.cpp
    Phase/PropsStore.cpp
    PhaseManager.cpp
)

set(INCLUDE_FILES
    App.hpp
    Component/BackgroundImage.hpp
    Component/Button.hpp
    ImageScaling.hpp
    SystemInfo.hpp
    Phase/CatBase.hpp
    Phase/StageSelection.hpp
    UnitData.hpp
    nlohmann/json.hpp
    DatabaseManager.hpp
    IStateful.hpp
    Phase.hpp
    Phase/Upgrade.hpp
    Phase/PropsStore.hpp
    PhaseManager.hpp
)

set(TEST_FILES
)
